### ISSUE TITLE
 HD notes crash the game on 8.0

### ISSUE THREAD

**Issue by dokilon** [Meme1079/NoteSkin-Selector#1]
when the HD notes are selected and I press space the game stops working.

**Comment by MemeFlavor** [comment]
send the script to me

**Comment by dokilon** [comment]
it is the normal script of 8.0 2.0 the hd notes were not completely programmed but I see that you solved it in 8.0 2.1

**Comment by MemeFlavor** [comment]
wut?

**Comment by dokilon** [comment]
I was wrong, only that in the beta 8.0 1.0 the preview of the hd notes was programmed but not its texture, but I think you already solved it in the last beta so I will close this issue
