### ISSUE TITLE
Crashes when using other scripts

### ISSUE THREAD

**Issue by SHADOWBOY9559959595** [Meme1079/NoteSkin-Selector#2]
well i usually use some script like the sara hud,song intro,change game over and the move screen with notes but when i added the chane noteskin and when i enter the song it just crashes the game and idk why pls can you tell me why and how to fix it? please :c

**Comment by MemeFlavor** [comment]
i don't know how to fix sorry, but you should stop using these script and _use other scripts_ that doesn't interfere the NoteSkin Script
