### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by NotEpik** [Meme1079/NoteSkin-Selector#8]
## Describe the bug
Pixel Note not working properly on the player's lane.

## To Reproduce
Fix it so it works on the player's lane properly

## Screenshots
Before:
![Friday Night Funkin'_ Psych Engine 7_15_2022 11_43_14 PM](https://user-images.githubusercontent.com/88980162/179270408-f6bebc03-cbb1-48a7-8ebb-6aa6c71981e7.png)

After:
![Friday Night Funkin'_ Psych Engine 7_15_2022 11_43_37 PM](https://user-images.githubusercontent.com/88980162/179270523-042eb3a7-1805-44f4-967c-97151b727650.png)

**Comment by MemeFlavor** [comment]
Thanks for reporting
